version: "3"
services:
  modsecurity:
    image: 'owasp/modsecurity-crs:apache'
    hostname: modsecurity
    restart: always
    ports:
      - 0.0.0.0:80:80
      #- 0.0.0.0:443:443
    environment:
      - BACKEND=http://10.10.0.30:80
      - BACKEND_WS=ws://10.10.0.30:80
      #- APACHE_ALWAYS_TLS_REDIRECT=on
      #- PROXY_SSL_CERT=/cert/archive/${DOMAIN:-csalab.cloud}/cert1.pem
      #- PROXY_SSL_CERT_KEY=/cert/archive/${DOMAIN:-csalab.cloud}/privkey1.pem
    volumes:
      - ./cert:/cert
    depends_on:
      - wordpress
    networks:
      internet:
        ipv4_address: 10.10.0.20

  wordpress:
    image: 'csalab/wordpress:latest'
    hostname: wordpress
    restart: always
    volumes:
      - data:/www
    depends_on:
      - database
    networks:
      internet:
        ipv4_address: 10.10.0.30
      no-internet:
        ipv4_address: 10.11.0.30

  debug:
    image: 'csalab/wordpress:debug'
    hostname: debug
    restart: always
    tty: true
    user: root
    volumes:
      - data:/www
    networks:
      internet:
        ipv4_address: 10.10.0.31
      no-internet:
        ipv4_address: 10.11.0.31

  database:
    image: 'mysql:8.2.0'
    hostname: database
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-MysqlPassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mysql:/var/lib/mysql
    networks:
      no-internet:
        ipv4_address: 10.11.0.40

networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

  no-internet:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.11.0.0/24
          gateway: 10.11.0.1

volumes:
  data: {}
  mysql: {}
