version: 2.1

parameters:
  workflow:
    type: enum
    default: auto
    description: The workflow to trigger.
    enum: [auto, manual]

executors:
  docker:
    docker:
      - image: cimg/base:stable

jobs:
  hadolint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Checking Dockerfile code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile || true
  build-wordpress:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
      - run:
          name: Setup apko
          command: |
            wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
            /usr/local/go/bin/go install chainguard.dev/apko@latest
      - run:
          name: Build and push wordpress debug images
          command: |
            /home/circleci/go/bin/apko publish \
              --quiet --sbom=false build/debug.yaml \
              $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug \
              $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug
      - run:
          name: Build and push wordpress latest images
          command: |
            /home/circleci/go/bin/apko build --quiet --sbom=false build/wordpress.yaml $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel wordpress.tar
            docker import wordpress.tar $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel
            docker push $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push \
              --build-arg REGISTRY_USER=$REGISTRY_USER \
              --build-arg DOCKER_REGISTRY=$DOCKER_REGISTRY/ \
              --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION \
              --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:latest \
              --platform linux/amd64,linux/arm64 -f Dockerfile .
            rm -rf go1.21.6.linux-amd64.tar.gz wordpress.tar
  grype-scan:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup grype
          command: |
            wget https://github.com/anchore/grype/releases/download/v0.74.0/grype_0.74.0_linux_amd64.deb
            sudo dpkg -i grype_0.74.0_linux_amd64.deb
      - run:
          name: Scanning latest image
          command: grype $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION
      - run:
          name: Scanning debug image
          command: grype $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug
  trivy-scan:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup trivy
          command: |
            wget https://github.com/aquasecurity/trivy/releases/download/v0.48.3/trivy_0.48.3_Linux-64bit.deb
            sudo dpkg -i trivy_0.48.3_Linux-64bit.deb
      - run:
          name: Scanning latest image
          command: trivy image $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION
      - run:
          name: Scanning debug image
          command: trivy image $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug

workflows:
  version: 2
  build-image-auto:
    when: { equal: [ auto, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - grype-scan
      - trivy-scan
  build-image-manual:
    when: { equal: [ manual, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-wordpress:
          requires:
            - hadolint
      - grype-scan:
          requires:
            - build-wordpress
      - trivy-scan:
          requires:
            - build-wordpress
