version: 2.1

parameters:
  workflow:
    type: enum
    default: auto
    description: The workflow to trigger.
    enum: [auto, manual]

executors:
  docker:
    docker:
      - image: cimg/base:stable

jobs:
  hadolint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Checking amd64 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile-amd64 || true
      - run:
          name: Checking arm64 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile-arm64 || true
  build-wordpress:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
      - run:
          name: Setup apko
          command: |
            wget https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
            /usr/local/go/bin/go install chainguard.dev/apko@latest
      - run:
          name: Build and push wordpress debug images
          command: |
            /home/circleci/go/bin/apko publish --sbom=false build/debug.yaml $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug
      - run:
          name: Build and push wordpress latest images
          command: |
            /home/circleci/go/bin/apko build --sbom=false build/wordpress.yaml $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel wordpress.tar
            docker import wordpress.tar $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --build-arg DOCKER_REGISTRY=$DOCKER_REGISTRY/ --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:latest --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f Dockerfile .
            rm -rf go1.21.6.linux-amd64.tar.gz wordpress.tar

workflows:
  version: 2
  build-image-auto:
    when: { equal: [ auto, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
  build-image-manual:
    when: { equal: [ manual, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-wordpress:
          requires:
            - hadolint
