version: 2.1

parameters:
  workflow:
    type: enum
    default: auto
    description: The workflow to trigger.
    enum: [auto, manual]

executors:
  docker:
    docker:
      - image: cimg/base:stable

jobs:
  hadolint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Checking amd64 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile-amd64 || true
      - run:
          name: Checking arm64 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile-arm64 || true
  build-wordpress:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
      - run:
          name: Build wordpress debug image
          command: |
            pwd
            docker run --rm -v ./:/work -w /work cgr.dev/chainguard/apko build build/debug.yaml $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug debug.tar
            docker load < debug.tar
            docker manifest create $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug --amend $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug-arm64 --amend $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug-amd64
            docker tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug
            docker push $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:debug
            docker push $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION-debug
      - run:
          name: Build and push wordpress latest images
          command: |
            docker run --rm -v ./:/work -w /work cgr.dev/chainguard/apko build build/wordpress.yaml $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel wordpress.tar
            docker load < wordpress.tar
            docker manifest create $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel --amend $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel-arm64 --amend $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:devel-amd64
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:$IMAGE_VERSION --tag $DOCKER_REGISTRY/$REGISTRY_USER/wordpress:latest --platform linux/amd64,linux/arm64 -f Dockerfile .

workflows:
  version: 2
  build-image-auto:
    when: { equal: [ auto, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
  build-image-manual:
    when: { equal: [ manual, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-wordpress:
          requires:
            - hadolint
